site_name: vendorless
site_url: https://liambindle.github.io/vendorless/
repo_url: https://github.com/LiamBindle/vendorless
edit_uri: blob/main/docs/
theme:
  name: material
  logo: assets/square-circle.png
  favicon: assets/favicon.ico
  palette:
    primary: white
    accent: deep purple
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
nav:
  - About:
    - Overview: index.md
    - rendering-blueprints.md
    - creating-packages.md
  - Blueprints: 
    - blueprints.md
  - Service Templates:
    - Volumes: volumes.md
    - Networks: networks.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          summary: true
          show_labels: false
          docstring_section_style: table
          filters: "public"
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          line_length: 80
          modernize_annotations: true
          show_signature: true
          members_order: source
          summary: true
    default_handler: python
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences